### ISSUE TITLE
I changed my src_addr

### ISSUE THREAD

**Issue by evilxyz** [houluy/UDP#1]
run `udp_recv(addr=('0.0.0.0', 6666), size=100)` in my  server, then
I changed my src_addr,  `udp_send(data='test', dest_addr=('server ip', 6666), src_addr=('8.8.8.8', 35869))`  and run in my client.

and i got my real ip in server...  so i want to know why ? 
I use wireshark capture packet, I saw whatever i wrote in src_addr, always change to my real ip, I dont know why. Is it the kernel problem ?

Platform:
    Linux 4.7.2-1-ARCH
    Python 3.5.2

**Comment by houluy** [comment]
The UDP protocol does not need the source IP or dest IP address in its header. All the IP addresses are filled automatically by IP Layer in the IP header. So whatever you write in the src_addr, your real IP will always be in the IP packet. However, UDP requires a pseudo header where source IP and dest IP address are kept, to compute the value of checksum. The pseudo header won't be transferred to the receiver, but if you write the wrong source address, the checksum process in the receiver won't pass.

In all, this is only a practicing code and bugs may be exist. I recommand to use UDP and TCP in socket module. 
Thank you:-)

**Comment by evilxyz** [comment]
Yeah, I really need review my network lesson, If i want to use random ip addr to send udp packet, how do i do this ?
by the way, i am doing some practice about dos,  it's ok.

**Comment by houluy** [comment]
You need to fill the IP packet manually. You can change the socket.IPPROTO_UDP into socket.IPPROTO_RAW to construct customized IP header.  
This post may be helpful for you [http://www.binarytides.com/raw-socket-programming-in-python-linux/](http://www.binarytides.com/raw-socket-programming-in-python-linux/)

**Comment by evilxyz** [comment]
Very thx, houluy !  It's so helpful for me !
: )

**Comment by houluy** [comment]
You' welcome
:-D
